### PR TITLE
Small PVR fixes

### PR DESCRIPTION
**Pull request by Leatherface75**
Small PVR fixes

### CODE REVIEW

**Comment by mikesilvo164** [comment]
Sorry but this isn't going to work. The extra room is there for am and pm. Your screenshots do not show that but for some it does.

You also have an extra merge commit so you would need to squash that if you do another PR.

**Comment by Leatherface75** [comment]
Ok i'm not so good in using git but will try to fix that if i make another PR.
Not checked am/pm thing but it's same as it was before and same as original and at same place as original Aeon-Nox from BigNoid.
The other fix is for some old crapchars in one of the ChannelViews.

**Comment by mikesilvo164** [comment]
Yeah, I noticed them on the Enigma 2 screen and will post an update sometime soon with those removed.

Instead of merging updates using the master branch rebase then create a new branch named anything you'd like to call it. Push your commit to that branch and open a PR using the same and it will have a clean history without the merge commits :smiley:

Thanks.

**Comment by mikesilvo164** [comment]
sorry not rebase it is a hard reset.

**Comment by Leatherface75** [comment]
Ok what i did was making a new branch from my master and then pusing my changes to that branch.
I checked am/fm setting and you're right but maybe 540 is enough.
Original Aeon-Nox had same problem.

**Comment by mikesilvo164** [comment]
I'm going to leave it the way it is for now. I plan on working on it some time in the future. The channel name and number on top do not need to match the ones below. They are all different sizes and channels can go from a single digit to 4 and that space doesn't look very good IMO 
Why do you keep bringing up original Aeon Nox? This is all from a PR and I already have many things that are different.

**Comment by Leatherface75** [comment]
Ok personally i think it looks better to have it matching with channelname.
I agree it looks better with bigger space between but at same time too much space without am/pm settings.
Sorry only mentioned that it was same problem there with am/pm with the old placement and that you were right.

**Comment by Leatherface75** [comment]
This is without any changes:
http://i.imgur.com/qGTG00Q.png

This is with 550 for channelname/programinfo
http://i.imgur.com/7aNdm1h.png

And with am/pm
http://i.imgur.com/ZWhqcG3.png

Not perfect but better atleast.

**Comment by mikesilvo164** [comment]
@Leatherface75 I just redid the InfoBars. Does it fix your issue with the 5 digits?

**Comment by Leatherface75** [comment]
Yes i saw that it looks better now.
New changes is nice but seems to need more space for long channelnames.
http://i.imgur.com/TBbPx3J.png

**Comment by mikesilvo164** [comment]
Working on it. Will push a new update in a few. Can you please check that the channel logo looks ok after the new update? If you notice any other issues you can post here or in the thread. I did see the post in the thread.

Thanks.

**Comment by Leatherface75** [comment]
Looks better now atleast with my channels and channelnumbers.

**Comment by Leatherface75** [comment]
Another issue is that starttime for current program in infobar starts to count backwards.
But i'm not sure if it's skin or Kodi itself.

**Comment by mikesilvo164** [comment]
Sounds like a Kodi bug. Skin has no control over what the INFOlabel says just where it goes :wink:

**Comment by Leatherface75** [comment]
Ok just as i thought hmms...
Another issue posted in forum :)

**Pull request closed without merging**
