### PR TITLE
Submenu background variables

### PR DESCRIPTION
**Pull request by Ignoble61**
Fixup variables and visibility conditions for submenu backgrounds.

Reverts part of your most recent commit - adding ControlGroup(9020).HasFocus to the home background variables - as, to be honest, I don't know what that does...

### CODE REVIEW

**Comment by mikesilvo164** [comment]
ControlGroup(9020).HasFocus fixes a black background when focused on the global search, playdvd, or eject icons or passing over it on the way to the widgets.

**Comment by Ignoble61** [comment]
Was that introduced by your original submenu background commit, as I don't see that with the variable changes I've made... (If it wasn't, I'll go and add that back in!)

**Comment by mikesilvo164** [comment]
Yes since I was using Control.HasFocus once you lose focus to either 9010 or 9000 it showed a black screen.

**Comment by Ignoble61** [comment]
In that case, with this PR it's no longer be necessary - if the submenu isn't focused or doesn't have a background it will always default to the main menu background.

**Comment by mikesilvo164** [comment]
Strange... It is still showing a black background for me using your new Variables :confused:
Maybe I need a restart instead of a skin reload...

**Comment by Ignoble61** [comment]
Wait, are you using one of the script.grab.fanart backgrounds? I haven't touched those variables, and can see that they could potentially lead to a black background :)

**Comment by mikesilvo164** [comment]
If you have the skin open, global search addon installed, global search icon not disabled in the settings, and are using the horizontal menu. There should be a magnifying glass icon near the time and weather. If you press up to focus that I get a black background.

**Comment by Ignoble61** [comment]
See if the latest commit fixes it. If it doesn't, I'll admit defeat and add the ControlGroup(9020) back in :smile:

**Comment by mikesilvo164** [comment]
I just tested and we are almost there... Right now everything works except the submenu fanart will not change if the submenu has single image or multiimage and the menu item does not.

**Comment by mikesilvo164** [comment]
My variables seem to work for all and the changes made to live_bg fix the playlist fanart...

**Comment by Ignoble61** [comment]
Typo in the autoscroll condition. Fixed that and squashed the commits.

**Comment by mikesilvo164** [comment]
Same issue Sir Bob.

I can reproduce by having the home menu item be a single image and submenu single image. I have it all working using my old [var](https://github.com/mikesilvo164/Aeon-Nox-SiLVO/blob/master/1080i/variables.xml), except some live background fanart isn't populating like recent movies.

**Comment by Ignoble61** [comment]
Can't reproduce it myself, but if you're happy with your old var then you're happy with your old var - I'll copy/paste it + update the PR imminently.

**Comment by mikesilvo164** [comment]
Spoke too soon, my vars still have a problem with the playlist as main menu and single image submenu...

**Comment by Ignoble61** [comment]
OK, lets break it down. So to recreate the issue (lets go with my vars here for the moment, just because I've got that branch active) I set both main and submenu items to a single image? What issue does that cause?

**Comment by mikesilvo164** [comment]
I don't care which var is used :smile:  I was just letting you know what was and wasn't working on my end in case it was helpful, I did not mean in any way to imply your was inferior or anything like that. I hope it did not come across that way...

**Comment by Ignoble61** [comment]
Didn't come across like that at all :smile:

**Comment by mikesilvo164** [comment]
Good :smile: I always try to word things carefully cause written things can so easily be taken out of context.

I haven't been switching branches I have just been downloading the Variables file and replacing it with my own and yours is now gone from your branch so I cannot test it since I just discarded the changes :laughing:

Probably a silly way to do it...

**Comment by Ignoble61** [comment]
And I'm often not careful enough with how I phrase things, particularly when crossing the language barrier :blush:

I've put my version of the vars back again. As I say, let me know what issue you're seeing and we'll see what can be done about it.

**Comment by mikesilvo164** [comment]
Ok, I saved a local copy of the vars now and am using that currently.

I have my music main menu item setup with different options for the submenu fanart. A live background, single image, multi image, and a playlist.

None set as the main menu item everything works except the playlist.
Single or multiimage everything works except playlist
script.grab.fanart or weather only live background works
live background nothing works except live background

No

**Comment by Ignoble61** [comment]
Playlist is the same typo I got wrong in the autoscroll, now fixed.

For live backgrounds/weather/script.grab.fanart (they're all the same code, ultimately), the main menu live background image is 'over' the submenu background image. The issue is the visibility conditions on lines 61 + 218 of the live backgrounds include - need to be extended so that, when 9010 has focus, has a background value, but it doesn't match a live background, they're hidden...

**Comment by mikesilvo164** [comment]
I think I am too tired... What now? :laughing:

**Comment by Ignoble61** [comment]
I think you give the latest commit a quick go, then if it doesn't work we both get some sleep and come at it fresh tomorrow :)

**Comment by mikesilvo164** [comment]
I already tested it and same issue with grab fanart but I have not tested the rest.

**Comment by Ignoble61** [comment]
Strange, that's working fine for me now. Still, I think best to look at it again tomorrow.

**Comment by mikesilvo164** [comment]
I tested my variable again and the only thing that doesn't work right is live background set as main.

I wonder why we are getting two different results though... You mentioned using only library nodes could that be it :question:

Just some food for thought while we both contemplate.

Thank your for the assistance once again Sir Bob :bow:

**Comment by Ignoble61** [comment]
I've been busy the last couple of days, but was just coming to take another look at this. Did you work out why we were getting such different results?

**Comment by mikesilvo164** [comment]
No, I have also been a little busy but my variable did not take into account a mouse and yours works so I figured I'd merge it now to fix the problem for mouse users and worry about the rest later :wink:

**Pull request merged**
