### PR TITLE
add TVGuide-button to Video-OSD and small fixes

### PR DESCRIPTION
**Pull request by walterheisenberg**
another possible Improvements:
- add TVGuide-Button to LiveTV-OSD
I used button-nr. 811, but placed it between Teletext (810) and (Channel-)EPG (809). The Playlist-png does fit best for this, as there is no TVGuide-png. 

- fixed the short appearance of the LiveTV-Bar after ChannelEPG is closed, mentioned here:
http://forum.kodi.tv/showthread.php?tid=210069&pid=2387406#pid2387406
I just moved <onclick>Dialog.Close(VideoOSD)</onclick> 2 lines to the top. So that it is closed before opening channelOSD.

### CODE REVIEW

**Comment by mikesilvo164** [comment]
The ActivateWindows should be that way but not sure about adding this button for a few reason. First it works better as a kemapped button on your remote (the "E" key) then it can be open/closed on command and that image could be confusing since it is used elsewhere. Don't mind adding it if there was a good image for the button but shouldn't the EPG button open that? I don't even like the look of the window that opens currently with the EPG button...

**Comment by walterheisenberg** [comment]
I thought about ppl, who does have not so much buttons on their remote ;)
1. Do you have the sources for the buttons, so that I can create a new button with GIMP?
2. For the channel-EPG, have a look here:
http://forum.kodi.tv/showthread.php?tid=183504&pid=2245375#pid2245375
First two pics. Don't know, if you like it more

**Comment by mikesilvo164** [comment]
I get that. Those "not many" button remotes are the norm with all those android boxes

1) No, those came from BigNoid. I have not learned how to do anything with images. I rely on others with those talents :wink:

2) The icon is better but the whole screen needs an update. Just doesn't look good IMHO... Not sure what to do with it ATM, need some time to think it over and come up with something. If you have any suggestions or ideas let me know :smiley:

**Comment by walterheisenberg** [comment]
I created 2 (4) new buttons for ChannelGuide and Guide (EPG) and I hope you like it. Feel free to make suggestions to make them better.

**Comment by walterheisenberg** [comment]
Did you had a look at the new buttons?
This PR can't be merged anymore, but maybe you can add the new buttons for ChannelGuide and Guide (EPG) ;)
The actual EPG-button does open the channel-EPG atm.

**Comment by walterheisenberg** [comment]
closed -> it was merged by BigNoid in AeonNox

**Pull request closed without merging**
