### PR TITLE
fix for aspectratio in Homescreen-widget info

### PR DESCRIPTION
**Pull request by walterheisenberg**
this fixes the wrong aspectratio for PVR-thumbs in homescreen widget "Recent Recordings", mentioned here:
http://forum.kodi.tv/showthread.php?tid=210069&pid=2383510#pid2383510

### CODE REVIEW

**Comment by mistervee** [comment]
I will have to look at that further. The fix cannot be committed as you have removed the $PARAM from the aspect which will cause issues in other views.

aspect is set in this block of code


		<control type="group">
			<visible>!IsEmpty(Container($PARAM[id]).ListItem.ChannelName)</visible>
			<include name="InfoContent">
				<param name="id">$PARAM[id]</param>
				<param name="Texture">$VAR[HomeWidget$PARAM[id]PosterVar]</param>
				<param name="Aspect">keep</param>
				<param name="Align">center</param>
				<param name="Title">$VAR[HomeWidget$PARAM[id]TitleVar]</param>
				<param name="SubTitle">$VAR[HomeWidget$PARAM[id]SubTitleVar]</param>
				<param name="Info1">$VAR[HomeWidget$PARAM[id]Info1Var]</param>
				<param name="Info2">$VAR[HomeWidget$PARAM[id]Info2Var]</param>
				<param name="Plot">$VAR[HomeWidget$PARAM[id]PlotVar]</param>
				<param name="widthBack">$PARAM[widthBack]</param>
				<param name="isSquare">true</param>
				<param name="Left">$PARAM[Left2]</param>
				<param name="Width">$PARAM[Width2]</param>
			</include>
		</control>

If a recording does not have a channel name associated with it, it wont work. 

So this is the issue
<visible>!IsEmpty(Container($PARAM[id]).ListItem.ChannelName)</visible>

**Comment by walterheisenberg** [comment]
I haven't removed anything, but added aspect ratio, because I didn't see it in the image-"block".
If there's another and better fix, please fix it as you like.

My reordings does all have a channel name, btw. It does at least show up, if I highlight it in "MyPVRRecordings".

**Comment by mistervee** [comment]
My mistake. The block of code you have changed is for the poster. Thought it was something else.

I have checked on the Jarvis branch and the visibility condition for the channel name Is not working. So I would assume the list item is not available for the widget.

It is provided by skin help service and I don't think many list items are available.

The only way to fix this with out breaking other things would be to make some crafty changes to the template.xml or kindly ask the author of skin helper service to add some more list items for the pvr widgets.

I'll see if I have time over the next few days.

**Comment by walterheisenberg** [comment]
OK, thx
What shall we do with this PR?
leave open or close

I posted a comment in Kodi-forums for marcelveldt. Maybe he can help

**Comment by mikesilvo164** [comment]
I'd say leave it open until you guys hear back from Marvel.

**Comment by mikesilvo164** [comment]
@mistervee Marcel said not possible and this adds aspectratio keep bot sure if it will mess up the cases... Or is that what you wanted to use to avoid that issue?

Close PR?

**Comment by walterheisenberg** [comment]
Sorry for the stupid question:
doesn't Posters also need aspect = keep? Skinhelper does scrape the Posters for the recorded TV-Shows. Isn't there a possibility to know, which image is used? e.g. Poster (from IMDB) or Thumb (from Recording)

The issue is still there, it should be "open" until it is finally solved.

**Comment by mistervee** [comment]
@mikesilvo164 @walterheisenberg 

Sorry for the late response and my lack of providing a clear solution,

Working on a new skin atm and wanting to keep this quiet for the time being btw (will pm you mike with details for comments in the coming weeks).

Just to be clear the only part that will need modifying are the visibility conditions in the block of code in Include_widgets.xml

Starting at line 76 <include name="Info"> and ending at line 132.

For the poster's I found the default of scale was the best as some poster images for certain plugins are not exactly a 1:1.5 ratio. They are close but if you keep the ratio they will have some empty borders and things look a little out of place.

As you can see there are three possible artwork type in the block. Poster (scale), Square (scale) and Square (keep).

All we need to find is a ListItem or property that is unique to tv recordings when no artwork is found for skin the helper service plugin (as this will return posters if found)  and adjust the visibility conditions to suit or possibly add another Include block with the required parameters.

The reason why it was coded this way was for mixed content. If you had latest music and moves in the one widget the aspect and size of the image would change suited to the focused item.

**Comment by walterheisenberg** [comment]
Isn't something like this possible:
SubString(ListItem.FolderPath,pvr://)
Idea taken from Skin.Helpers README:
https://github.com/marcelveldt/script.skin.helper.service#pvr-images-inside-lists

**Comment by mikesilvo164** [comment]
Maybe... Alternatively we might be able to delete
`<propertySettings property="widgetType" templateonly="True" />`
from the overrides file and use the widget type but not sure if that means the type will actually be written to the includes file or not.

I haven't really looked into it but the template seems to be using the widgetType to set keep for PVR aspect so the same might be able to be used for the Widget info. Maybe... :wink:

**Comment by mistervee** [comment]
Spot on mike. If the template only is set to false (or deleted) the property will be written to the skin shortcuts include xml and then can be used as a visibility condition. 

I cant find a solution that will cover all scenarios for the pvr widgets. It's just me liking everything to line up on the artwork and have no empty borders.

So a compromise would be to use the widget type (PVR) as a visibility condition and ensure the aspect ratio is scale and centered x and y. All that means is when skin helper service downloads a poster for the PVR it will center it in a square box and have some empty borders.

**Comment by mikesilvo164** [comment]
@mistervee Please do not feel the need to apologize, we all have "better" things to do... For me it is hanging out with my 2 kids so for others it could be whatever they prefer to do :wink:

One of my favorite things about you is how everything needs to be perfect cause I have these moments where I will move things a few pixels, here and there, back and forth, just so it looks "right" to me... That must be my OCD taking over :stuck_out_tongue_winking_eye:

When you started with the Widgets I just had my baby girl so I didn't really learn all the template stuff but recently I found some time to look it over so this just came to me as I was still trying to figure it all out.

Lastly, I am intrigued about you starting a skin from scratch. Seems like a lot of work but I can't wait to see what you come up with :smile:

**Comment by mikesilvo164** [comment]
@walterheisenberg Can you please test if the last commit fixes this issue?

**Comment by walterheisenberg** [comment]
unfortunately not
But I can live with this. You can close the issue, if you want

**Comment by mikesilvo164** [comment]
@walterheisenberg Please try again with the latest.

If it is working, you can close.

I don't want to close without fixing it :wink:

**Comment by walterheisenberg** [comment]
fixed!
Thx

**Pull request closed without merging**
