### PR TITLE
Change channelnumber digits from 3 to 4 digits

### PR DESCRIPTION
**Pull request by Leatherface75**
This fixes the issue for people with satellite or IPTV there you often can have a few thousand channels in channellist.

### CODE REVIEW

**Comment by mikesilvo164** [comment]
@Leatherface75 I had too many changes I was working on without pushing so this, unfortunately, became impossible to merge. I did, however, change things around and added 4 digit support. Please check if the latest is looking and working well for you. If so, please close this PR.

😃

**Comment by Leatherface75** [comment]
You forgot the channel selection with 'c' key but in the other one and EPG it looks good.

**Comment by mikesilvo164** [comment]
Should be good to go now.

If so please close PR.

Thanks

**Comment by Leatherface75** [comment]
Now everything seems ok thanks

**Pull request closed without merging**
