### PR TITLE
add PlotOutline to LiveTV Infobar

### PR DESCRIPTION
**Pull request by walterheisenberg**
with option to disable it, if someone doesn't like it.

### CODE REVIEW

**Comment by mikesilvo164** [comment]
Not going to add trhis to the InfoBar. It is already available when toggling plot info.

**Comment by walterheisenberg** [comment]
Let me explain, why I added this and please rethink your decission:
Wha about users, who enabled "Switch channels with 'OK'" in TV/PVR settings?
They can press up/down on fullscreen LiveTV and see what TV program is running on another channel in  infobar without switching to the channel.
Then PlotOutline is very useful, because of the additional info about episode title, genre and year it provides.

Sure you have it in plot info too, but on switching channels or looking through channels (see above) you don't see plot info and you have to toogle it to get it. This is very difficult, when you have <5s autoclosing of the infobar.

For this 2 reasons, I added it (from a user perspective)
Thx

**Comment by mikesilvo164** [comment]
Hmmm... Actually a reasonable explanation for an addition. I just do not prefer the implementation of where it is located in this PR so not sure the best way to add it but the current version just does not sit "right" with me...

Suggestions?

**Comment by walterheisenberg** [comment]
what do you mean "sit right"?
The position of PlotOutline in infobar or the position of the new code?

**Comment by mikesilvo164** [comment]
Where I see it in the InfoBar... No complaints about the actual code position... That would be annoyingly weird even for me and my issues :wink: however I did not look that deeply into it after I tested the PR.

**Comment by walterheisenberg** [comment]
We can delete the option, I just added it for ppl who don't like PlotOutline ;) so they can disable it. 
If we leave this option in, it can be spread (?) to other PlotOutline appearances

**Comment by walterheisenberg** [comment]
Here is a different version with a new top-bar:
http://imgur.com/yZRJago
I moved things around to get more space for plotoutline ...
The PR isn't updated yet -> What do you think?

**Comment by mikesilvo164** [comment]
@walterheisenberg Sorry 😞 but I don't care for the current look with this PR.

I am not a fan of disconnecting that info and placing it in a "topbar"...

**Comment by walterheisenberg** [comment]
That was only a alternative brainstorm from me. 

Then we should stay with this (first) PR and discuss where to put it:
1. place it after "Player.Title" as in this PR
2. do we need the date _and_ the weather? If not, I can place the date above the actual BG-box, expand all to the full width and place PlotOutline after "Player.Title". As it is in the pic above
3. place the date and weather in a box at the top right. Below the button bar.
4. make the channel logo smaller and place something above: date, time etc.
5. place it somewhere else? Suggestions?
What do you think about putting the channel name above the box, like in the picture above.
We agree to remove the setting, correct?

This are just a few suggestions to get some space for PlotOutline ;)

**Pull request closed without merging**
